services:
  app:
    build:
      context: ./app
    expose:
      - "80"

  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/templates/default.conf.template
        read_only: true
      - type: bind
        source: ./nginx/static
        target: /usr/share/nginx/html
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - app
